/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcessoClienteRouteImport } from './routes/acesso-cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCapacidadeRouteImport } from './routes/_authenticated/capacidade'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedCustosRouteImport } from './routes/_authenticated/custos'
import { Route as AuthenticatedCustosClientesRouteImport } from './routes/_authenticated/custos-clientes'
import { Route as AuthenticatedCustosEquipeRouteImport } from './routes/_authenticated/custos-equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedHorasRouteImport } from './routes/_authenticated/horas'
import { Route as AuthenticatedKpisRouteImport } from './routes/_authenticated/kpis'
import { Route as AuthenticatedMeuTrabalhoRouteImport } from './routes/_authenticated/meu-trabalho'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRiscosRouteImport } from './routes/_authenticated/riscos'
import { Route as AuthenticatedSatisfacaoRouteImport } from './routes/_authenticated/satisfacao'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalProjetoIdRouteImport } from './routes/portal/$projetoId'
import { Route as PortalSenhaRouteImport } from './routes/portal/senha'
import { Route as RelatorioTokenRouteImport } from './routes/relatorio.$token'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedClientesClienteIdRouteImport } from './routes/_authenticated/clientes/$clienteId'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos/index'
import { Route as AuthenticatedProjetosProjetoIdRouteImport } from './routes/_authenticated/projetos/$projetoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoClienteRoute = AcessoClienteRouteImport.update({
  id: '/acesso-cliente',
  path: '/acesso-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCapacidadeRoute = AuthenticatedCapacidadeRouteImport.update({
  id: '/capacidade',
  path: '/capacidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustosRoute = AuthenticatedCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustosClientesRoute =
  AuthenticatedCustosClientesRouteImport.update({
    id: '/custos-clientes',
    path: '/custos-clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustosEquipeRoute =
  AuthenticatedCustosEquipeRouteImport.update({
    id: '/custos-equipe',
    path: '/custos-equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHorasRoute = AuthenticatedHorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKpisRoute = AuthenticatedKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuTrabalhoRoute =
  AuthenticatedMeuTrabalhoRouteImport.update({
    id: '/meu-trabalho',
    path: '/meu-trabalho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiscosRoute = AuthenticatedRiscosRouteImport.update({
  id: '/riscos',
  path: '/riscos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSatisfacaoRoute = AuthenticatedSatisfacaoRouteImport.update({
  id: '/satisfacao',
  path: '/satisfacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjetoIdRoute = PortalProjetoIdRouteImport.update({
  id: '/$projetoId',
  path: '/$projetoId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSenhaRoute = PortalSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => PortalRoute,
} as any)
const RelatorioTokenRoute = RelatorioTokenRouteImport.update({
  id: '/relatorio/$token',
  path: '/relatorio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesClienteIdRoute =
  AuthenticatedClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosProjetoIdRoute =
  AuthenticatedProjetosProjetoIdRouteImport.update({
    id: '/projetos/$projetoId',
    path: '/projetos/$projetoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-cliente': typeof AcessoClienteRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/capacidade': typeof AuthenticatedCapacidadeRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/custos-clientes': typeof AuthenticatedCustosClientesRoute
  '/custos-equipe': typeof AuthenticatedCustosEquipeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/horas': typeof AuthenticatedHorasRoute
  '/kpis': typeof AuthenticatedKpisRoute
  '/meu-trabalho': typeof AuthenticatedMeuTrabalhoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/riscos': typeof AuthenticatedRiscosRoute
  '/satisfacao': typeof AuthenticatedSatisfacaoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/portal/$projetoId': typeof PortalProjetoIdRoute
  '/portal/senha': typeof PortalSenhaRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-cliente': typeof AcessoClienteRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/capacidade': typeof AuthenticatedCapacidadeRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/custos-clientes': typeof AuthenticatedCustosClientesRoute
  '/custos-equipe': typeof AuthenticatedCustosEquipeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/horas': typeof AuthenticatedHorasRoute
  '/kpis': typeof AuthenticatedKpisRoute
  '/meu-trabalho': typeof AuthenticatedMeuTrabalhoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/riscos': typeof AuthenticatedRiscosRoute
  '/satisfacao': typeof AuthenticatedSatisfacaoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/portal/$projetoId': typeof PortalProjetoIdRoute
  '/portal/senha': typeof PortalSenhaRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/portal': typeof PortalIndexRoute
  '/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso-cliente': typeof AcessoClienteRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/capacidade': typeof AuthenticatedCapacidadeRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/custos': typeof AuthenticatedCustosRoute
  '/_authenticated/custos-clientes': typeof AuthenticatedCustosClientesRoute
  '/_authenticated/custos-equipe': typeof AuthenticatedCustosEquipeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/horas': typeof AuthenticatedHorasRoute
  '/_authenticated/kpis': typeof AuthenticatedKpisRoute
  '/_authenticated/meu-trabalho': typeof AuthenticatedMeuTrabalhoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/riscos': typeof AuthenticatedRiscosRoute
  '/_authenticated/satisfacao': typeof AuthenticatedSatisfacaoRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/portal/$projetoId': typeof PortalProjetoIdRoute
  '/portal/senha': typeof PortalSenhaRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/clientes/$clienteId': typeof AuthenticatedClientesClienteIdRoute
  '/_authenticated/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-cliente'
    | '/auth'
    | '/portal'
    | '/reset-password'
    | '/calendario'
    | '/capacidade'
    | '/configuracoes'
    | '/cronograma'
    | '/custos'
    | '/custos-clientes'
    | '/custos-equipe'
    | '/dashboard'
    | '/documentos'
    | '/equipe'
    | '/financeiro'
    | '/horas'
    | '/kpis'
    | '/meu-trabalho'
    | '/relatorios'
    | '/riscos'
    | '/satisfacao'
    | '/tarefas'
    | '/portal/$projetoId'
    | '/portal/senha'
    | '/relatorio/$token'
    | '/portal/'
    | '/clientes/$clienteId'
    | '/projetos/$projetoId'
    | '/clientes/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-cliente'
    | '/auth'
    | '/reset-password'
    | '/calendario'
    | '/capacidade'
    | '/configuracoes'
    | '/cronograma'
    | '/custos'
    | '/custos-clientes'
    | '/custos-equipe'
    | '/dashboard'
    | '/documentos'
    | '/equipe'
    | '/financeiro'
    | '/horas'
    | '/kpis'
    | '/meu-trabalho'
    | '/relatorios'
    | '/riscos'
    | '/satisfacao'
    | '/tarefas'
    | '/portal/$projetoId'
    | '/portal/senha'
    | '/relatorio/$token'
    | '/portal'
    | '/clientes/$clienteId'
    | '/projetos/$projetoId'
    | '/clientes'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso-cliente'
    | '/auth'
    | '/portal'
    | '/reset-password'
    | '/_authenticated/calendario'
    | '/_authenticated/capacidade'
    | '/_authenticated/configuracoes'
    | '/_authenticated/cronograma'
    | '/_authenticated/custos'
    | '/_authenticated/custos-clientes'
    | '/_authenticated/custos-equipe'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/horas'
    | '/_authenticated/kpis'
    | '/_authenticated/meu-trabalho'
    | '/_authenticated/relatorios'
    | '/_authenticated/riscos'
    | '/_authenticated/satisfacao'
    | '/_authenticated/tarefas'
    | '/portal/$projetoId'
    | '/portal/senha'
    | '/relatorio/$token'
    | '/portal/'
    | '/_authenticated/clientes/$clienteId'
    | '/_authenticated/projetos/$projetoId'
    | '/_authenticated/clientes/'
    | '/_authenticated/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoClienteRoute: typeof AcessoClienteRoute
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RelatorioTokenRoute: typeof RelatorioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-cliente': {
      id: '/acesso-cliente'
      path: '/acesso-cliente'
      fullPath: '/acesso-cliente'
      preLoaderRoute: typeof AcessoClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capacidade': {
      id: '/_authenticated/capacidade'
      path: '/capacidade'
      fullPath: '/capacidade'
      preLoaderRoute: typeof AuthenticatedCapacidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos': {
      id: '/_authenticated/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof AuthenticatedCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos-clientes': {
      id: '/_authenticated/custos-clientes'
      path: '/custos-clientes'
      fullPath: '/custos-clientes'
      preLoaderRoute: typeof AuthenticatedCustosClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos-equipe': {
      id: '/_authenticated/custos-equipe'
      path: '/custos-equipe'
      fullPath: '/custos-equipe'
      preLoaderRoute: typeof AuthenticatedCustosEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/horas': {
      id: '/_authenticated/horas'
      path: '/horas'
      fullPath: '/horas'
      preLoaderRoute: typeof AuthenticatedHorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kpis': {
      id: '/_authenticated/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof AuthenticatedKpisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-trabalho': {
      id: '/_authenticated/meu-trabalho'
      path: '/meu-trabalho'
      fullPath: '/meu-trabalho'
      preLoaderRoute: typeof AuthenticatedMeuTrabalhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riscos': {
      id: '/_authenticated/riscos'
      path: '/riscos'
      fullPath: '/riscos'
      preLoaderRoute: typeof AuthenticatedRiscosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/satisfacao': {
      id: '/_authenticated/satisfacao'
      path: '/satisfacao'
      fullPath: '/satisfacao'
      preLoaderRoute: typeof AuthenticatedSatisfacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/$projetoId': {
      id: '/portal/$projetoId'
      path: '/$projetoId'
      fullPath: '/portal/$projetoId'
      preLoaderRoute: typeof PortalProjetoIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/senha': {
      id: '/portal/senha'
      path: '/senha'
      fullPath: '/portal/senha'
      preLoaderRoute: typeof PortalSenhaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/relatorio/$token': {
      id: '/relatorio/$token'
      path: '/relatorio/$token'
      fullPath: '/relatorio/$token'
      preLoaderRoute: typeof RelatorioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$clienteId': {
      id: '/_authenticated/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/$projetoId': {
      id: '/_authenticated/projetos/$projetoId'
      path: '/projetos/$projetoId'
      fullPath: '/projetos/$projetoId'
      preLoaderRoute: typeof AuthenticatedProjetosProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCapacidadeRoute: typeof AuthenticatedCapacidadeRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedCustosRoute: typeof AuthenticatedCustosRoute
  AuthenticatedCustosClientesRoute: typeof AuthenticatedCustosClientesRoute
  AuthenticatedCustosEquipeRoute: typeof AuthenticatedCustosEquipeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHorasRoute: typeof AuthenticatedHorasRoute
  AuthenticatedKpisRoute: typeof AuthenticatedKpisRoute
  AuthenticatedMeuTrabalhoRoute: typeof AuthenticatedMeuTrabalhoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRiscosRoute: typeof AuthenticatedRiscosRoute
  AuthenticatedSatisfacaoRoute: typeof AuthenticatedSatisfacaoRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedClientesClienteIdRoute: typeof AuthenticatedClientesClienteIdRoute
  AuthenticatedProjetosProjetoIdRoute: typeof AuthenticatedProjetosProjetoIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCapacidadeRoute: AuthenticatedCapacidadeRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedCustosRoute: AuthenticatedCustosRoute,
  AuthenticatedCustosClientesRoute: AuthenticatedCustosClientesRoute,
  AuthenticatedCustosEquipeRoute: AuthenticatedCustosEquipeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHorasRoute: AuthenticatedHorasRoute,
  AuthenticatedKpisRoute: AuthenticatedKpisRoute,
  AuthenticatedMeuTrabalhoRoute: AuthenticatedMeuTrabalhoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRiscosRoute: AuthenticatedRiscosRoute,
  AuthenticatedSatisfacaoRoute: AuthenticatedSatisfacaoRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedClientesClienteIdRoute: AuthenticatedClientesClienteIdRoute,
  AuthenticatedProjetosProjetoIdRoute: AuthenticatedProjetosProjetoIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteChildren {
  PortalProjetoIdRoute: typeof PortalProjetoIdRoute
  PortalSenhaRoute: typeof PortalSenhaRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalProjetoIdRoute: PortalProjetoIdRoute,
  PortalSenhaRoute: PortalSenhaRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoClienteRoute: AcessoClienteRoute,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RelatorioTokenRoute: RelatorioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
